# https://docs.docker.com/compose/compose-file/
version: '3.8'

services:
  # Kind cluster
  devcontainer-features:
    image: "alephzai.azurecr.io/devcontainers/$DEVCONTAINER_PROJECT_NAME:latest"
    container_name: $DEVCONTAINER_PROJECT_NAME-devspace
    labels: ["ai.alephz.role=$DEVCONTAINER_FEATURES_PROJECT_NAME"]
    env_file: .env
    environment:
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
      PULSE_SERVER: $PULSE_SERVER
    # https://docs.docker.com/compose/compose-file/build/#build-definition
    # Includes https://github.com/devcontainers/features/tree/main/src/common-utils
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # https://github.com/dotnet/dotnet-docker/tree/main/src/runtime-deps
        IMAGE: mcr.microsoft.com/devcontainers/base:ubuntu
    networks:
      - default
    cap_add:
      - SYS_ADMIN  # This is typically required for systemd
      - DAC_READ_SEARCH  # This may also be required in some cases for systemd
    security_opt:
      - seccomp:unconfined  # This may also be required in some cases for systemd
    volumes:
      - ../..:/workspaces:cached
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp/.X11-unix:$X11
      - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
networks:
  default:
