# https://docs.docker.com/compose/compose-file/
version: '3.8'

services:
  # Kind cluster
  devcontainer-features:
    image: devcontainer-features
    container_name: devcontainer-features-devspace
    labels: [ "ai.alephz.role=devcontainer-features" ]
    env_file: .env
    # https://github.com/microsoft/wslg/blob/main/samples/container/Containers.md
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
      - PULSE_SERVER=${PULSE_SERVER:-/tmp}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/tmp}
      - LIB_WSL=${LIB_WSL:-/tmp}
      - MNT_WSLG=${MNT_WSLG:-/tmp}
      - X11_SOCKET=${X11_SOCKET:-/tmp}
    devices:
      - /dev/dxg
    # https://docs.docker.com/compose/compose-file/build/#build-definition
    # Includes https://github.com/devcontainers/features/tree/main/src/common-utils
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # https://github.com/dotnet/dotnet-docker/tree/main/src/runtime-deps
        IMAGE: mcr.microsoft.com/devcontainers/base:ubuntu
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [ gpu ]
    networks:
      - default
    # https://medium.com/swlh/docker-and-systemd-381dfd7e4628
    volumes:
      - ../..:/workspaces:cached
      - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR:cached
      - $MNT_WSLG:/mnt/wslg:cached
      - $X11_SOCKET:/tmp/.X11-unix
      - type: bind
        source: $LIB_WSL
        target: /usr/lib/wsl
        read_only: true
        consistency: cached
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
        consistency: cached
networks:
  default:
