# https://docs.docker.com/compose/compose-file/
version: '3.8'

services:
  # Kind cluster
  devcontainer-features:
    image: devcontainer-features
    container_name: devcontainer-features-devspace
    labels: [ "ai.alephz.role=devcontainer-features" ]
    env_file: .env
    # https://github.com/microsoft/wslg/blob/main/samples/container/Containers.md
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN_DEVCONTAINER_FEATURES
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - PULSE_SERVER=$PULSE_SERVER
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    devices:
      - /dev/dxg
    # https://docs.docker.com/compose/compose-file/build/#build-definition
    # Includes https://github.com/devcontainers/features/tree/main/src/common-utils
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # https://github.com/dotnet/dotnet-docker/tree/main/src/runtime-deps
        IMAGE: mcr.microsoft.com/devcontainers/base:ubuntu
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [ gpu ]
    networks:
      - default
    # https://medium.com/swlh/docker-and-systemd-381dfd7e4628
    volumes:
      - ../..:/workspaces:cached
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ${XDG_RUNTIME_DIR:-/tmp}:${XDG_RUNTIME_DIR:-/tmp}
      - $LIB_WSL:/usr/lib/wsl
      - $MNT_WSLG:/mnt/wslg
      - $X11_SOCKET:/tmp/.X11-unix
networks:
  default:
