# example=https://github.com/devcontainers/features/blob/main/.github/workflows/release.yaml
name: "Release dev container features"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yaml'
      - 'src/*/devcontainer-feature.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check last commit message
        id: last_commit
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -dc '[:alnum:] ')
          echo "LAST_COMMIT_MESSAGE=$LAST_COMMIT_MESSAGE" >> "$GITHUB_ENV"

      - name: Check should continue
        id: should_continue
        run: |
          echo "SHOULD_CONTINUE=$(if [[ "$LAST_COMMIT_MESSAGE" == *"Automated devcontainer features update"* ]]; then echo true; else echo false; fi)" >> "$GITHUB_ENV"

      - name: "Publish"
        uses: devcontainers/action@v1
        if: ${{ env.SHOULD_CONTINUE == 'true' }}
        with:
          publish-features: "true"
          base-path-to-features: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
