#example=https://github.com/devcontainers/features/blob/main/.github/workflows/test-all.yaml
name: "CI - Test Features"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: [
            "color",
            "hello",
            "homebrew"
        ]
        baseImage:
          [
            "ubuntu:focal",
            "ubuntu:jammy",
            "ubuntu:bionic",
            "debian:11",
            "debian:10",
            "mcr.microsoft.com/devcontainers/base:ubuntu",
            "mcr.microsoft.com/devcontainers/base:debian",
          ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Run common-utils"
        run: sudo INSTALL_ZSH=false INSTALL_OH_MY_ZSH=false UPGRADE_PACKAGES=false USERNAME=vscode USER_UID=1000 USER_GID=1000 ./rund -id devcontainers/features common-utils install
      
      - name: "Run useer check"
        run: cat /etc/passwd
      
      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-scenarios:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: [
            "color",
            "hello",
            "homebrew"
        ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Run common-utils"
        run: sudo INSTALL_ZSH=false INSTALL_OH_MY_ZSH=false UPGRADE_PACKAGES=false USERNAME=vscode USER_UID=1000 USER_GID=1000 ./rund -id devcontainers/features common-utils install
      
      - name: "Run useer check"
        run: cat /etc/passwd
      
      - name: "Testing '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated  .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Run common-utils"
        run: sudo INSTALL_ZSH=false INSTALL_OH_MY_ZSH=false UPGRADE_PACKAGES=false USERNAME=vscode USER_UID=1000 USER_GID=1000 ./rund -id devcontainers/features common-utils install
      
      - name: "Run useer check"
        run: cat /etc/passwd
      
      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
