name: "Manual - Test Features"
on:
  workflow_dispatch:
    inputs:
      features:
        description: "List of features to execute tests against"
        required: true
        default: "go dotnet"
      baseImage:
        description: "Base image"
        required: true
        default: "ubuntu:focal"
      logLevel:
        description: "Log Level (info/debug/trace)"
        required: true
        default: "info"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
  
      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Run common-utils"
        run: echo $UID"; pushd .devcontainer/dependencies/devcontainers/features/src/common-utils; sudo INSTALL_ZSH=false INSTALL_OH_MY_ZSH=false UPGRADE_PACKAGES=false USERNAME=vscode USER_UID=2037 USER_GID=2037 ./install.sh; popd
      
      - name: "Testing '${{ github.event.inputs.features }}' against '${{ github.event.inputs.baseImage }}'"
        run: devcontainer features test --features ${{ github.event.inputs.features }} --base-image ${{ github.event.inputs.baseImage }} --log-level ${{ github.event.inputs.logLevel }} .
