name: "PR - Test Updated Features"
on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            color: ./**/color/**
            hello: ./**/hello/**
            homebrew: ./**/homebrew/**

  test:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJSON(needs.detect-changes.outputs.features) }}
        baseImage:
          [
            "ubuntu:focal",
            "ubuntu:jammy",
            "ubuntu:bionic",
            "debian:11",
            "debian:10",
            "mcr.microsoft.com/devcontainers/base:ubuntu",
            "mcr.microsoft.com/devcontainers/base:debian",
          ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Run common-utils"
        run: sudo INSTALL_ZSH=false INSTALL_OH_MY_ZSH=false UPGRADE_PACKAGES=false USERNAME=vscode USER_UID=1002 USER_GID=1002 ./rund -id devcontainers/features common-utils install
      
      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test  --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-scenarios:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJSON(needs.detect-changes.outputs.features) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Run common-utils"
        run: sudo INSTALL_ZSH=false INSTALL_OH_MY_ZSH=false UPGRADE_PACKAGES=false USERNAME=vscode USER_UID=1002 USER_GID=1002 ./rund -id devcontainers/features common-utils install
      
      - name: "Testing '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated  .
