name: Update DevContainer

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update devcontainer.json
        run: |
          jq '.name = "DevContainer Features v'${{ github.run_id }}'"' .devcontainer/devcontainer.json > temp.json && mv temp.json .devcontainer/devcontainer.json

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update devcontainer.json"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update devcontainer.json"
          title: "Update devcontainer.json"
          body: "This PR updates the devcontainer.json file with the latest commit hash."
          branch: "update-devcontainer-v${{ github.run_id }}"
