name: Update DevContainer

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update-devcontainer.yml'
      - '.devcontainer/**'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a PR for DevContainer
        id: push_image_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex
          echo "Start."

          # Configure git and Push updates
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git config pull.rebase false

          branch=automated-devcontainer-update-$GITHUB_RUN_ID
          git checkout -b $branch
          message='Automated devcontainer.json update'

          # Update devcontainer.json
          jq '.name = "DevContainer Features ${devcontainerId} v${{ github.run_id }}"' .devcontainer/devcontainer.json > temp.json && mv temp.json .devcontainer/devcontainer.json

          # Add / update and commit
          git add .devcontainer/devcontainer.json
          git commit -m "$message [skip ci]" || export NO_UPDATES=true

          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                /repos/${GITHUB_REPOSITORY}/pulls \
                -f title="$message" \
              -f body="$message" \
              -f head="$branch" \
              -f base='main'
          fi
