name: Update Features

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq and moreutils (sponge)
        run: sudo apt-get install -y jq moreutils

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check last commit message
        id: last_commit
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "::set-output name=message::$LAST_COMMIT_MESSAGE"
 
      - name: Update devcontainer-feature.json
        run: |
          if [[ "${{ steps.last_commit.outputs.message }}" == *"Automated devcontainer-feature.json update"* ]]; then
            echo "Last commit was an automated devcontainer-feature.json update, skipping version update..."
            exit 0
          fi

          CHANGED_FEATURES=$(git diff --name-only HEAD~1 HEAD -- ./src | awk -F'/' '{print $2}' | uniq)
          for feature in $CHANGED_FEATURES; do
              if [[ -d "./src/$feature" ]]; then
                  json_file="src/$feature/devcontainer-feature.json"
                  jq '.version = (.version | split(".") | map(tonumber) | .[2] += 1 | join("."))' "$json_file" | sponge "$json_file"
              else
                  echo "No directory found for $feature"
                  exit 1
              fi
          done

      - name: Create a PR for Features
        id: push_image_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Start."
      
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git config pull.rebase false
      
          branch=automated-features-update-$GITHUB_RUN_ID
          git checkout -b $branch
          message='Automated devcontainer-feature.json update'
      
          git add src/**/devcontainer-feature.json
          git commit -m 'Automated devcontainer-feature.json update' || export NO_UPDATES=true
      
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                /repos/${GITHUB_REPOSITORY}/pulls \
                -f title="$message" \
                -f body="$message" \
                -f head="$branch" \
                -f base='main'
          fi
