#example=https://github.com/devcontainers/features/blob/main/.github/workflows/validate-metadata-files.yml
name: "Validate devcontainer-feature.json files"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/validate-metadata-files.yml'
      - 'src/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"
